In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import variation 

In [7]:
df=pd.read_csv('amir_deals.csv')
df.head()

Unnamed: 0    product   client status   amount  num_users
0           1  Product F  Current    Won  7389.52         19
1           2  Product C      New    Won  4493.01         43
2           3  Product B      New    Won  5738.09         87
3           4  Product I  Current    Won  2591.24         83
4           5  Product E  Current    Won  6622.97         17

In [8]:
# Calculate the interquartile range
q75, q25 = np.percentile(df['amount'], [75 ,25])
iqr = q75 - q25
iqr

2801.3299999999995

In [9]:
# Calculate the satandard deviation
stan_dev=np.std(df['amount'])
print(stan_dev)

2052.383697078496


In [13]:
#calculate the coeffiecient of variation
arr = np.random.randn(3, 3)

print ("array : \n", arr)

# rows: axis = 0, cols: axis = 1

print ("\nVariation at axis = 0: \n", variation(arr, axis = 0))

print ("\nVariation at axis = 1: \n", variation(arr, axis = 1))


array : 
 [[-1.42729921 -1.41519881  0.97698032]
 [-0.47743531  0.23175347  0.12440909]
 [-0.28919657  0.48875336  0.02874638]]

Variation at axis = 0: 
 [-0.68110928 -3.64265126  1.13149258]

Variation at axis = 1: 
 [-1.8180695  -7.72074768  4.19648611]
