In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# flipping 1 coin with 50% chance for heads once
from scipy.stats import binom
binom.rvs(1,0.5,size=1)

array([0])

In [4]:
# flipping 2 coin with 50% chance for heads 10 times
binom.rvs(2,0.5,size=10)

array([1, 2, 0, 0, 1, 2, 2, 0, 0, 1])

In [6]:
np.random.binomial(4,0.5)

2

In [9]:
# Get a sample from poisson distribution
np.random.poisson(6,size=5)

array([8, 5, 5, 6, 4])

In [ ]:
np.random.normal(133, 8, size=10)