In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
x=[2,4,6,9,14]
y=[32,64,72,81,172]
np.cov(x,y)[0][1]

235.5

In [4]:
x = np.arange(10, 20)
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
print(x)
print(y)

[10 11 12 13 14 15 16 17 18 19]
[ 2  1  4  5  8 12 18 25 96 48]


In [5]:
r = np.corrcoef(x, y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

In [6]:
x_col = pd.Series(range(10, 20))
y_col= pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
x_col.corr(y_col) 

0.7586402890911867